### ISSUE TITLE
Lunar 2020 connecting but not communicating

### ISSUE THREAD

**Issue by darzism** [zweckj/acaia#3] opened 2023-11-21 01:46 UTC
Hi,
Thanks for your hard work on this!
I have successfully connected it to my Lunar 2020 (log it showing its successfully connecting every morning, but lunar is not indicating the connection), but I'm not recieving any information and can send any commands. Let me know if I can do anything to help debugging.

Quick note, I couldn't connect using "older model" option, so I used the default option.
Thanks!
darz

**Comment by zweckj** [comment] 2023-11-21 09:04
Should be a duplicate of #2 as those scale use the same communication. Try the pre-release version, enable debug logging and check if you can find any meaningful information in the logs.

**Closed as completed by zweckj** 2023-11-21 09:04 UTC
